"""add not null

Revision ID: 17f1ca18ebe5
Revises: 1c7780ff56f9
Create Date: 2025-10-24 11:58:09.161123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f1ca18ebe5'
down_revision = '1c7780ff56f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('departments', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('departments', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exam_judgements', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exam_master', 'exam_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exam_results', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exam_results', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exam_results', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exams', 'exam_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exams', 'exam_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exams', 'exam_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'school_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'admission_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subject_master', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subject_scores', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_scores', 'subject_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_scores', 'deviation_value',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('universities', 'university_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'login_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'login_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('universities', 'university_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subject_scores', 'deviation_value',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('subject_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_scores', 'subject_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_scores', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject_master', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'admission_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'school_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exams', 'exam_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exams', 'exam_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exams', 'exam_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_results', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_results', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_results', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_master', 'exam_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exam_judgements', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('departments', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('departments', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('departments', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
