"""sync models

Revision ID: 1c7780ff56f9
Revises: 
Create Date: 2025-10-24 10:53:53.658188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7780ff56f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_master',
    sa.Column('exam_code', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exam_code')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('subject_master',
    sa.Column('subject_code', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('subject_code')
    )
    op.create_table('universities',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('university_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_code', sa.Integer(), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_code'], ['exam_master.exam_code'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('exam_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('exam_judgements',
    sa.Column('judgement_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('preference_order', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('judgment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], ),
    sa.PrimaryKeyConstraint('judgement_id')
    )
    op.create_table('subject_scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('deviation_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subject_master.subject_code'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_scores')
    op.drop_table('exam_judgements')
    op.drop_table('exam_results')
    op.drop_table('exams')
    op.drop_table('departments')
    op.drop_table('users')
    op.drop_table('universities')
    op.drop_table('subject_master')
    op.drop_table('students')
    op.drop_table('exam_master')
    # ### end Alembic commands ###
