"""Facultyのunique不要だった

Revision ID: 24f063cce703
Revises: 50354595314f
Create Date: 2025-10-27 10:57:55.662287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f063cce703'
down_revision = '50354595314f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('faculties_faculty_name_key'), 'faculties', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('faculties_faculty_name_key'), 'faculties', ['faculty_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
