"""add name_kana to students

Revision ID: 28f6a3190a18
Revises: a6aa4b54465f
Create Date: 2025-11-04 14:09:59.631666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f6a3190a18'
down_revision = 'a6aa4b54465f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name_kana', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'name_kana')
    # ### end Alembic commands ###
