"""判定の種類追加

Revision ID: 43d31daccf9f
Revises: c79db3b92a4f
Create Date: 2025-11-06 08:23:56.309203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d31daccf9f'
down_revision = 'c79db3b92a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_judgements', sa.Column('judgement_kyote', sa.String(), nullable=True))
    op.add_column('exam_judgements', sa.Column('judgement_niji', sa.String(), nullable=True))
    op.add_column('exam_judgements', sa.Column('judgement_sougou', sa.String(), nullable=True))
    op.drop_column('exam_judgements', 'judgement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_judgements', sa.Column('judgement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exam_judgements', 'judgement_sougou')
    op.drop_column('exam_judgements', 'judgement_niji')
    op.drop_column('exam_judgements', 'judgement_kyote')
    # ### end Alembic commands ###
