"""Faculty追加

Revision ID: 495354a2a2bd
Revises: 777b2a1c7aac
Create Date: 2025-10-25 14:42:52.345866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495354a2a2bd'
down_revision = '777b2a1c7aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('faculty_id'),
    sa.UniqueConstraint('faculty_name')
    )
    op.add_column('departments', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('departments_university_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'faculties', ['faculty_id'], ['faculty_id'])
    op.drop_column('departments', 'university_id')
    op.drop_column('departments', 'faculty_name')
    op.create_unique_constraint(None, 'exam_master', ['exam_name'])
    op.drop_constraint(op.f('exam_results_uploaded_by_fkey'), 'exam_results', type_='foreignkey')
    op.create_unique_constraint(None, 'universities', ['university_name'])
    op.create_unique_constraint(None, 'users', ['login_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'universities', type_='unique')
    op.drop_constraint(None, 'subject_master', type_='unique')
    op.create_foreign_key(op.f('exam_results_uploaded_by_fkey'), 'exam_results', 'users', ['uploaded_by'], ['user_id'])
    op.drop_constraint(None, 'exam_master', type_='unique')
    op.add_column('departments', sa.Column('faculty_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('departments', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_university_id_fkey'), 'departments', 'universities', ['university_id'], ['university_id'])
    op.drop_column('departments', 'faculty_id')
    op.drop_table('faculties')
    # ### end Alembic commands ###
