"""uploaded by 削除

Revision ID: 50354595314f
Revises: 495354a2a2bd
Create Date: 2025-10-26 17:16:32.858107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50354595314f'
down_revision = '495354a2a2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_results', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_results', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
