"""add sort_key to exam_master

Revision ID: 6e1888cc3b49
Revises: 43d31daccf9f
Create Date: 2025-11-17 14:08:15.616582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1888cc3b49'
down_revision = '43d31daccf9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_master', sa.Column('sort_key', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_master', 'sort_key')
    # ### end Alembic commands ###
