"""学年をIntからStringに

Revision ID: 777b2a1c7aac
Revises: 17f1ca18ebe5
Create Date: 2025-10-24 12:24:43.663567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777b2a1c7aac'
down_revision = '17f1ca18ebe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'grade',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'grade',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
