"""judgement綴りミス修正

Revision ID: a6aa4b54465f
Revises: 24f063cce703
Create Date: 2025-10-27 16:44:54.545006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aa4b54465f'
down_revision = '24f063cce703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_judgements', sa.Column('judgement', sa.String(), nullable=True))
    op.drop_column('exam_judgements', 'judgment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_judgements', sa.Column('judgment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exam_judgements', 'judgement')
    # ### end Alembic commands ###
