"""add status to students

Revision ID: c79db3b92a4f
Revises: 28f6a3190a18
Create Date: 2025-11-04 15:01:47.029746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79db3b92a4f'
down_revision = '28f6a3190a18'
branch_labels = None
depends_on = None


def upgrade():
    # 既存行にデフォルトを入れてからNOT NULLに変更
    op.add_column('students', sa.Column('status', sa.String(), nullable=True, server_default='在籍'))
    # サーバデフォルトで既存行が更新された後、NOT NULLへ
    op.alter_column('students', 'status', nullable=False)
    # サーバデフォルトは不要なので外す
    op.alter_column('students', 'status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'status')
    # ### end Alembic commands ###
